---
title: "PFI - Thompson Report"
author: "Maggie Johnson, Andee Kaplan, Colin Lewis-Beck, Michael Price, and Pete Walsh"
date: "11/24/2014"
output:
  pdf_document:
    includes:
      in_header: extra/preamble.tex
    number_sections: yes
bibliography: extra/refs.bib
---

```{r libraries, echo=FALSE, message=FALSE, warning=FALSE}
## Add all libraries used loaded here
## Do not load libraries within individual parts
library(knitr)
library(plyr)
library(dplyr)
library(tidyr)
library(ggvis)
library(ggplot2)
library(gridExtra)
library(xtable)
library(reshape2)
```

```{r options, echo=FALSE, message=FALSE}
opts_chunk$set(message = FALSE, warning = FALSE, fig.height = 4, echo = FALSE)
ggplot2::theme_set(theme_bw(base_family = "serif"))
```

```{r data, echo=FALSE, message=FALSE}
## Pull in data here for all parts to use
## Do not pull in data within parts
dat <- read.csv("../data/PFI_clean.csv")
var <- read.csv("../data/var_map.csv")
countyYield<-read.csv("../data/BooneYields.csv")
```

```{r code, echo=FALSE, message=FALSE}
## Source in external code chunks here
## Do not source external code within parts
```

# Introduction
```{r intro, child='parts/intro.Rmd', eval=TRUE}
```

## Data
```{r data, child='parts/data.Rmd', eval=TRUE}
```

## Goals of Analysis
```{r goals, child='parts/goals.Rmd', eval=TRUE}
```

# Expenses
```{r expense, child='parts/expenses.Rmd', eval=TRUE}
```

# Yield
```{r yield, child='parts/yield.Rmd', eval=TRUE}
```

# Income
```{r income, child='parts/income.Rmd', eval=TRUE}
```

# Conclusions
```{r conclusion, child='parts/conclusions.Rmd', eval=TRUE}
```

# References