---
title: "Thompson Yields"
author: "Evan “Pete” Walsh"
date: "November 19, 2014"
output: html_document
runtime: shiny
---

<hr>

###Load data and packages

```{r message=FALSE}
pfi <- read.csv("/Users/marianwaitwalsh/GitHub/PFI/data/PFI_clean.csv")
library(dplyr)
library(tidyr)
library(reshape2)
library(ggvis)
library(ggplot2)
```

###Organize the data

```{r}
yields <- pfi %>%
  filter(item_type %in% c("Expense"), farmer == "Thompson") %>% 
  spread(item, value) %>% 
  select(-c(5))

yields <- yields %>% mutate(year_before = year - 1) %>%
  left_join(select(yields, 1:4), 
            by=c("field_id" = "field_id", "year_before" = "year")) %>%
  select(-c(2,38))

# Get crop yields
value <- pfi %>% 
  filter(item_type %in% c("Unit Quantity"), farmer == "Thompson") %>%
  select(c(1,3,7))

# Add crop yields to yields df
yields <- yields %>% 
  left_join(value, by = c("field_id" = "field_id", "year" = "year")) %>%
  rename(crop = crop.x, prev_crop = crop.y, yield = value) %>%
  select(-3)

# Reorder variables
yields <- yields[,c(2,1,3,36,37,4:35)]
```

###Seperate out yields by crop

```{r}
corn <- yields %>% filter(crop == "Corn") %>%
  select(-3)
sb <- yields %>% filter(crop == "SB") %>%
  select(-3)
oats <- yields %>% filter(crop == "Oats") %>%
  select(-3)
hay <- yields %>% filter(crop == "Hay") %>%
  select(-3)
```

```{r message=FALSE}
require(gridExtra)
plot1 <- qplot(prev_crop, yield, data=filter(corn, !is.na(prev_crop))) +
  ggtitle("Corn")
plot2 <- qplot(prev_crop, yield, data=filter(sb, !is.na(prev_crop))) + 
  ggtitle("SB")
plot3 <- qplot(prev_crop, yield, data=filter(oats, !is.na(prev_crop))) +
  ggtitle("Oats")
plot4 <- qplot(prev_crop, yield, data=filter(hay, !is.na(prev_crop))) + 
  ggtitle("Hay")
grid.arrange(plot1, plot2, 
             plot3, plot4, ncol=2)
```

```{r defineWidget, fig.height=3, echo=FALSE}
source("widget.R")
```

```{r}
widget(yields)
``` 