---
title: 'PFI: Yields'
author: "Evan “Pete” Walsh"
date: "October 27, 2014"
output: pdf_document
---

\subsection*{Yields for SB and Corn in acre buschel per pound.}

Read data and load libraries.

```{r message=FALSE}
pfi <- read.csv("GitHub/PFI/data/PFI_clean.csv")
weather <- read.csv("GitHub/PFI/data/IA_annual_rainfall_raw.csv")
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
```

Subset the ```PFI``` data.

```{r}
yields <- pfi %>%
  filter(item_type == "Unit Quantity", crop %in% c("Corn","SB")) %>%
  select(-c(item, item_type)) %>%
  group_by(field_id, year)
```

Clean the weather data and join with ```yields```.

```{r warning=FALSE}
wBoone <- weather %>%
  filter(stationName == "Boone") %>% 
  gather(key, value, 5:373) %>%
  separate(key, into = c("year", "key"), sep = "\\_") %>%
  spread(key, value) %>%
  select(year, MAXT, MINT, PREC)

wBoone$year <- sapply(wBoone$year, FUN = function(x) extract_numeric(x))
yields2 <- inner_join(yields, wBoone, by = "year")
yields2$MAXT <- as.numeric(yields2$MAXT)
yields2$MINT <- as.numeric(yields2$MINT)
yields2$PREC <- as.numeric(yields2$PREC)
```

```{r fig.height=4, fig.width=7}
head(yields2)
qplot(PREC, value, data=yields2, colour=farmer, shape=farmer,
      facets=~crop) + geom_smooth(method="lm", se=F) +
  ylab("Yield")
qplot(MAXT, value, data=yields2, colour=farmer, shape=farmer,
      facets=~crop) + geom_smooth(method="lm", se=F)+
  ylab("Yield")
qplot(MINT, value, data=yields2, colour=farmer, shape=farmer,
      facets=~crop) + geom_smooth(method="lm", se=F)+
  ylab("Yield")
```

Fields by year for Thompson that were used for ```SB``` or ```corn```.

```{r}
# pfi %>% 
#   filter(item_type == "Unit Quantity", crop %in% c("Corn","SB"),
#          farmer == "Thompson") %>%
#   group_by(year, field_id) %>%
#   select(1:4)
```

```{r}
yields3 <- pfi %>%
  filter(item_type == "Expense", crop  %in% c("Corn", "SB")) %>% 
  spread(item, value) %>% 
  select(-c(5))
for (i in 5:36) {
  yields3[,i] <- yields3[,i] != 0
}
```
